#!/usr/bin/env python

import sys
import os
from colorama import Fore, Style
import shutil


def main():
    for i in sys.argv[1:]:
        if not os.path.isdir(f"/usr/lib/IOI/Hydra/modules/{i}"):
            print(f"{Fore.RED}Module {i} not found{Style.RESET_ALL}")
            continue
        shutil.rmtree(f"/usr/lib/IOI/Hydra/modules/{i}")
        print(f"{Fore.GREEN}Module {i} removed{Style.RESET_ALL}")

if __name__ == "__main__":
    main()
